CREATE DATABASE IF NOT EXISTS dawson_olympics;

USE dawson_olympics;

CREATE TABLE IF NOT EXISTS games (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
image VARCHAR(255),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stadiums (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
location VARCHAR(100) NOT NULL,
image VARCHAR(255),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
name VARCHAR(100) NOT NULL,
location VARCHAR(100) NOT NULL,
role INT NOT NULL DEFAULT 1,
image VARCHAR(255),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS news (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
game_id INT,
title VARCHAR(100) NOT NULL,
about TEXT NOT NULL,
created_by INT NOT NULL,
type VARCHAR(20) NOT NULL DEFAULT 'general',
event_date DATETIME,
image VARCHAR(255),
stadium_id INT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(game_id) REFERENCES games(id),
FOREIGN KEY(created_by) REFERENCES users(id),
FOREIGN KEY(stadium_id) REFERENCES stadiums(id)
);

CREATE TABLE IF NOT EXISTS news_images (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
news_id INT,
image VARCHAR(255),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(news_id) REFERENCES news(id)
);

CREATE TABLE IF NOT EXISTS mclasses (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
game_id INT,
stadium_id INT,
location VARCHAR(100),
title VARCHAR(100),
about TEXT,
mfrom DATETIME,
mto DATETIME,
image VARCHAR(255),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(game_id) REFERENCES games(id)
);

CREATE TABLE IF NOT EXISTS user_mclasses (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
user_id INT,
class_id INT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(user_id) REFERENCES users(id),
FOREIGN KEY(class_id) REFERENCES mclasses(id)
);
